CREATE TABLE Usernames (
    UserId UNIQUEIDENTIFIER PRIMARY KEY,
    Username VARCHAR(50) NOT NULL
);
go
CREATE TABLE Emails (
    UserId UNIQUEIDENTIFIER PRIMARY KEY,
    Email VARCHAR(50) NOT NULL
);
go
CREATE TABLE Addresses (
    UserId UNIQUEIDENTIFIER PRIMARY KEY,
    Address VARCHAR(200) NOT NULL
);